<a href="https://colab.research.google.com/github/deivid-cp/tfg/blob/main/setting_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import zipfile
import os

# Paths of the directory
PROJECT_ROOT_DIR = os.getcwd()
PROJECT_ROOT_DIR = os.path.join(PROJECT_ROOT_DIR, "proyecto")
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images")
DATA_PATH = os.path.join(PROJECT_ROOT_DIR, "datasets")

In [6]:
# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
os.makedirs(IMAGES_PATH, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

In [7]:
# Where to unzip data
os.makedirs(DATA_PATH, exist_ok=True)

def unzip_data(zipfile_name, directory_to_extract_to = DATA_PATH):

    path_to_zip_file = os.path.join(PROJECT_ROOT_DIR, zipfile_name)

    with zipfile.ZipFile(path_to_zip_file, 'r') as zip_ref:
        zip_ref.extractall(directory_to_extract_to)

unzip_data(os.path.join(PROJECT_ROOT_DIR, "pan21-author-profiling-test-2021-04-12.zip"))
unzip_data(os.path.join(PROJECT_ROOT_DIR, "pan21-author-profiling-training-2021-03-14.zip"))

In [8]:
# Data processing
# Extracting data from .xml files to Pandas DataFrame and saving them as .csv

import pandas as pd
import xml.etree.ElementTree as ET

# A list of two components with dictionaries in each of them with which we will
# create the dataframes, in the first component the training set and in the
# second one the test set
L = [{'user' : [], 'raw_text' : [], 'language' : [], 'class' : []},
 {'user' : [], 'raw_text' : [], 'language' : [], 'class' : []}]

# A list with the directories we will iterate, the last component is the current
# directory and the previous ones the ones we have already iterated to reach the
# current one
paths_list = [DATA_PATH]

for dir1 in os.listdir(paths_list[0]):    # os.listdir(path) returns a list of the
                                          # names of the files inside the given path
    if dir1 == 'pan21-author-profiling-training-2021-03-14':
        set_type = 0    # The training set will be in the first component
    elif dir1 == 'pan21-author-profiling-test-2021-04-12':
        set_type = 1    # The test set will be in the second component
    else:    # In order to skip the file '.ipynb_checkpoints' created by Jupyter
        continue
    paths_list.append(os.path.join(paths_list[-1], dir1))
    for dir2 in os.listdir(paths_list[-1]):
        if dir2 == "en":
            lng = 'english'
        else:
            lng = 'spanish'
        paths_list.append(os.path.join(paths_list[-1], dir2))
        for user in os.listdir(paths_list[-1]):
            if user == '.ipynb_checkpoints' or user == 'truth.txt':
                continue
            tree = ET.parse(os.path.join(paths_list[-1], user))
            root = tree.getroot()

            tweets = []

            # The root attributes are a dictionary and the value of the key 'class'
            # is a string with a '0' (no hate speech) or a '1' (hate speech)
            cls = int(root.attrib['class'])

            for documents in root:
                for document in documents:
                    tweets.append(document.text)
            L[set_type]['user'].append(user)
            L[set_type]['raw_text'].append(tweets)
            L[set_type]['language'].append(lng)
            L[set_type]['class'].append(cls)
        del paths_list[-1]
    del paths_list[-1]

# We create the whole training and test datasets and save them in a .csv
training_set = pd.DataFrame(L[0])
test_set = pd.DataFrame(L[1])
training_set.to_csv(os.path.join(DATA_PATH, "training_set.csv"), index=False)
test_set.to_csv(os.path.join(DATA_PATH, "test_set.csv"), index=False)

# We create the english training and test datasets and save them in a .csv
training_set_english = training_set.loc[training_set['language'] == 'english']
test_set_english = test_set.loc[test_set['language'] == 'english']
training_set_english.to_csv(os.path.join(DATA_PATH, "training_set_english.csv"), index=False)
test_set.to_csv(os.path.join(DATA_PATH, "test_set_english.csv"), index=False)

# We create the spanish training and test datasets and save them in a .csv
training_set_spanish = training_set.loc[training_set['language'] == 'spanish']
test_set_spanish = test_set.loc[test_set['language'] == 'spanish']
training_set_spanish.to_csv(os.path.join(DATA_PATH, "training_set_spanish.csv"), index=False)
test_set_spanish.to_csv(os.path.join(DATA_PATH, "test_set_spanish.csv"), index=False)

In [9]:
training_set.head()

,user,raw_text,language,class
0,9cff4936f8479d53fcbb63f2524c5ad8.xml,[It’s pissing me off how desperate Paige is wt...,english,0
1,e30b87c8fa34a1ac077d7b286000bc06.xml,"[Ima be 20 hrs from Houston now ugh, Fuga pa V...",english,1
2,f91fa8ecdd2440eb163516769573f24a.xml,[me and kayleigh just waking up lol we finna b...,english,1
3,44e25d1ec3f786a696e0eb5b33b8325b.xml,"[WHO THE OG'S? #URL#, ATE THE WRONG PUSSY GOTT...",english,1
4,7c18d72ba1eb9c787f166df788e1b521.xml,[if somone told me that you could teach a 15 m...,english,0

In [10]:
training_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user      400 non-null    object
 1   raw_text  400 non-null    object
 2   language  400 non-null    object
 3   class     400 non-null    int64
dtypes: int64(1), object(3)
memory usage: 12.6+ KB

In [11]:
test_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user      200 non-null    object
 1   raw_text  200 non-null    object
 2   language  200 non-null    object
 3   class     200 non-null    int64
dtypes: int64(1), object(3)
memory usage: 6.4+ KB

In [12]:
training_set_english.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user      200 non-null    object
 1   raw_text  200 non-null    object
 2   language  200 non-null    object
 3   class     200 non-null    int64
dtypes: int64(1), object(3)
memory usage: 7.8+ KB

In [13]:
training_set_spanish.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 200 to 399
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user      200 non-null    object
 1   raw_text  200 non-null    object
 2   language  200 non-null    object
 3   class     200 non-null    int64
dtypes: int64(1), object(3)
memory usage: 7.8+ KB

In [14]:
test_set_english.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user      100 non-null    object
 1   raw_text  100 non-null    object
 2   language  100 non-null    object
 3   class     100 non-null    int64
dtypes: int64(1), object(3)
memory usage: 3.9+ KB

In [15]:
test_set_spanish.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 100 to 199
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   user      100 non-null    object
 1   raw_text  100 non-null    object
 2   language  100 non-null    object
 3   class     100 non-null    int64
dtypes: int64(1), object(3)
memory usage: 3.9+ KB

In [16]:
training_set['raw_text']

0      [It’s pissing me off how desperate Paige is wt...
1      [Ima be 20 hrs from Houston now ugh, Fuga pa V...
2      [me and kayleigh just waking up lol we finna b...
3      [WHO THE OG'S? #URL#, ATE THE WRONG PUSSY GOTT...
4      [if somone told me that you could teach a 15 m...
                             ...
395    [Paolo Maldini, aishh que hombre 😍😍 La eleganc...
396    [Honor a los Leales. Y a nuestros Caídos: un f...
397    [Si van a hacer públicos los citados de las ca...
398    [muero de amor con milo 🥰, vieron cuando les d...
399    [RT #USER#: Cómo va el efecto Illa en Cataluny...
Name: raw_text, Length: 400, dtype: object

In [17]:
training_set['raw_text'][0]

['It’s pissing me off how desperate Paige is wtfffffff #HASHTAG#',
 'Being wholesome 💫 #URL#',
 'Lmfaooooooooooooooooo I’m imagining wtf she doing #URL#',
 '#USER# I’m waiting on 2 more final exam grades lmaoooo lettuce pray!',
 'RT #USER#: When I die please don’t text me “tell me it’s not true😭” cuz I will not reply.',
 'RT #USER#: When they ask me how many LLCs ima register w/ my stimmy #URL#',
 'Last term grades rolling in. I really got a 100 on a final 😂😂😂 I deserve....something....',
 'Could y’all fucking pleaseeeeee 😭😭😭😭😭😭😭😭😭😭😭😭😭 #URL#',
 'RT #USER#: I ain’t even complaining about gas nomo.. This $20 going ina tank whether it’s 1.99 or 2.50...😂😂',
 'RT #USER#: Same thing w having kids . Everybody shouldnt be allowed to have one. U gotta be able to qualify for that',
 'RT #USER#: &amp; give some of y’all children their stimmy money so they can stop breaking in ppl cars plz. stop being greedy!',
 'RT #USER#: Phase 3 in New Orleans? Boy they bout to have to tear gas niggas to make them leave shamrock',
 'RT #USER#: Dinner with Meek Mill&gt;&gt;&gt;',
 'LMFAOOOOOOOOOOOOOOOOO GO TO HELL #URL#',
 '#USER# #USER# #USER# Lmaooooooo our tuition over 4 years is $375K plus interest......so honestly probably more than 450K smh',
 '#USER# #USER# Friends 4L 🤞🏽💚',
 '#USER# Can’t wait! 🥰',
 '#USER# #USER# I do.....plus 400K more 🥴🥴🥴',
 'RT #USER#: Followers with a sense of humor.. &gt;&gt;&gt;',
 'RT #USER#: 🗣🗣pipe it up!!!!!',
 '#USER# Wait a minute! Lowered it to what?',
 'RT #USER#: Anyone in the Conyers, Covington, Madison area need a job? I need a Classroom Aide. $15-17/hr',
 'RT #USER#: how serious is New Orleans about festival season #URL#',
 'HOLLERINGGGGGGGGG at these damn shoes omg #URL#',
 'RT #USER#: brunch/day drinking &gt; the club',
 '#USER# Oh you rich?',
 '#USER# Why?! What happened?',
 'RT #USER#: Me training for Mardi Gras 2022',
 'RT #USER#: Please please please don’t let LLC Twitter near your Stimulus check.',
 '#USER# We giving whole ass vaccines and not a damn $1 more 😂😂😂😂😂',
 'BLOCKED AS FUCK #URL#',
 'Ain’t got a damn dime lmao #URL#',
 'RT #USER#: me forcing my man to drink knowing he only smoke #URL#',
 '#USER# Exactly why they don’t wanna give us shit 😂😂😂😂😂😂',
 'When I see the $2800 plus taxes: #URL#',
 'RT #USER#: She finna be wearing less and goin out more. Take care bro.',
 'RT #USER#: 70 degrees plus tequila is a calm 90. So it’s basically summer #URL#',
 'RT #USER#: Time to upgrade fellas. Be the hoe you’re truly meant to be this summer. #URL#',
 'RT #USER#: clubhouse so lame. everybody think they somebody lol',
 'RT #USER#: Come be one of God’s Saints',
 '#USER# They have a valid point lmaooooooo',
 '#USER# I cannot stop laughing bruh',
 'I beg your damn pardon? 😂😂😂😂 #URL#',
 '*after the 2nd bite lmao #URL#',
 'RT #USER#: Honeybuns really just stopped tasting good one random day 😂',
 '#USER# Yes. I’ve heard enough lmao',
 'Honey, where have you been? #URL#',
 'RT #USER#: fam I’ve been dying for hours 😂😂😂😂 #URL#',
 '“Tweets aren’t loading right now” never sit right with my spirit lmao',
 'I’m mad I missed the mess. Somebody fill me in. #HASHTAG# #HASHTAG#',
 'Let me get back on #URL#',
 'RT #USER#: Social media is really a horrible place.',
 'That’s what y’all do on Clubhouse fr? I’m sorry I wasted somebody invite 😂',
 'They still gone be mad by Tuesday?! #URL#',
 'I ain’t been missing out on shit lmaooooooo #URL#',
 'I missed all the damn mess!',
 'I can’t damn breathe lmaooooooo #URL#',
 'BITCH EXCUSE ME??????? #HASHTAG#',
 '#USER# I’m confused af. My mic muted?! Hot we just observing?',
 'Deleting it after this lmao #URL#',
 '“Girl shut the fuck up lying”',
 'I don’t damn know lmao idk what this shit is. I just clicked the link to the mess and that came up #URL#',
 'Girl Ima miss all the mess. I’m only here for the girls that’s fightinggggggg #URL#',
 '#USER# Tf is this? #URL#',
 '#USER# BJ! PLEASE RECORD THIS LMAO',
 'Stop right there has me pissy pissy!',
 'I AM FUCKING HOLLERING #URL#',
 '#USER# Where is the messssss',
 '#USER# bruh what is happening? Lmao',
 '#USER# No Mrs. Richard. Go walk on the beach lmao',
 'RT #USER#: i am so tired of seeing yall walk lmfaoooo',
 'Bitch that’s my kind of investigating. But I wouldn’t put that shit on here if it happened lmao',
 'And end up humiliating themselves too #URL#',
 'RT #USER#: Y’all let me kno the tea, I’m not getting on CH😂😂😂😂',
 'RT #USER#: Sometimes it’s just good to hold your L’s in silence......',
 'Go screen record it best cousin! #URL#',
 'Y’all pick and choose when y’all wanna laugh or advocate.',
 'RT #USER#: ppl be tweeting stuff i wouldn’t even talk to myself about',
 'RT #USER#: lol the first thing you do when you get cheated on is tell your timeline. y’all are truly slow man.',
 '#USER# Girl I don’t have this shit! Get on Twitter live lmaooooooo',
 'Please do! Screen record lmaooooooo #URL#',
 'So much for National Women’s Day lmaooooooo',
 'RT #USER#: Oh we bout to get the real story now',
 'RT #USER#: So....you posted your cheater...now what do we do w dis information?',
 'RT #USER#: Y’all be mad at the Cheaté and not the Cheater. That don’t sit right with me.',
 'I think the fuck not you trick ass bitch #URL#',
 'Let me turn my notifications on. Tweet me before you start lmao #URL#',
 'RT #USER#: come to me as as woman and i’m gonna come to you as Norman Freeman. #URL#',
 'I missed Twitter lmaooooooo',
 'IT IS NATIONAL WOMENS DAY!!!!!! #USER#',
 'Cheat back 💕',
 '#USER# Baby this still going on. Hop on the ride sis, let’s go read!',
 'Flewed out stories BYKE 😍😍😍😍',
 'RT #USER#: Oh now wait a minute my baby. #URL#',
 '*broke black ass Republicans at that #URL#',
 'Give me back my girls then you give me back my life!! #USER# #USER#',
 'They don’t have bank accounts 🥺 #URL#',
 'RT #USER#: Why the fuck do y’all not have Zelle?',
 'RT #USER#: when i say my ex is petty, i mean it 😭 #URL#',
 'I’m lit. I deserved this too lol Winter term down. One term closer to being a Dr.....',
 'RT #USER#: This kinda toxic. #URL#',
 'COVID about to raw dog Texas. #URL#',
 'RT #USER#: So Texas just bout to raw dog covid like that?',
 'One more exam tomorrow 💪🏽',
 'RT #USER#: No Stimmy coming. They giving you Outside instead. So now you in the club with one drink for 4 hours.',
 'RT #USER#: Clubs about to be playing the hell outta Mask Off LMAOOOOOOO',
 '#USER# And she keep fucking smiling which pisses me the fuck off! Fuck you grinning for ma’am?!!',
 'RT #USER#: Paige really gonna show up at meeting with Chris and he BM!!? #HASHTAG# #URL#',
 'Where the hell are Paige’s friends????!! #HASHTAG# #URL#',
 'RT #USER#: Here he go whispering in her ear and her ass just a smiling #HASHTAG# #URL#',
 'RT #USER#: The fact that she continued to sleep with him.... This can’t be real. #HASHTAG# #HASHTAG#',
 'RT #USER#: Chris ordered them jeans off the women’s section at Fashionnova #HASHTAG# #HASHTAG# #URL#',
 'RT #USER#: This is the WHOLE ENTIRE WORLD right now listening to Paige talk to Pastor Cal. #HASHTAG# #HASHTAG#',
 'RT #USER#: Likeeee ma’am. He showed you who he was a million times??!! #HASHTAG# #HASHTAG# #URL#',
 'RT #USER#: Paige: “I’m done looking crazy” Also Paige: #HASHTAG# #URL#',
 'RT #USER#: i love pussy corn chips on menz',
 'I’m speechless fr #URL#',
 'RT #USER#: No one in Meek’s camp was like “aye bruh that ain’t the one”. Ion like that',
 'Wow Meek. Just....wow.',
 '*retarded as fuck #URL#',
 'RT #USER#: That’s a lot of candles for somebody that owe me $2,000',
 '#USER# Been blocked since that game. #URL#',
 'RT #USER#: No room in my life for people who aren’t understanding. We are grown and we have our days. We all going through shit',
 'Never stood a damn chance #URL#',
 '#USER# Perfect! I’ve already done that. That’s why I can’t see 💛',
 'What this shit fucking say?! #URL#',
 '#USER# Valid fucking question here! Why is no one concerned???',
 'RT #USER#: Everything flew off like Mr Potato head.',
 'RT #USER#: #USER# In the middle of a Panda Express?! Wild',
 'RT #USER#: How you pass down CTE',
 "RT #USER#: #USER# Her: Can y'all turn this weak ass song off. Me: Or what👊🏽",
 'Something definitely wrong with her.....like mentally. #URL#',
 'I just wanna do ratchet things with my ratchet friends!',
 'RT #USER#: You got desires✨ #URL#',
 'RT #USER#: I need a vacation so bad.',
 '#USER# Just in case you forgot 😂😂',
 'RT #USER#: I claim it 👏🏾',
 '#USER# Oh Ima do that anyway cause that’s how I am ex best lmaooo',
 'LMFAOOOOOOOOOOOOOOOOO I felt that “Nigga what?” with my whole soul #URL#',
 'Another sleepless night.',
 'RT #USER#: Baldwin &amp; Co, a new Black-owned coffee &amp; bookstore, opened today in New Orleans #URL#',
 'RT #USER#: Lord this baby finna act just like her😭 #URL#',
 'What else they was supposed to do?! #URL#',
 '#USER# Them long nights man. Long nights.',
 'Only 5 more to go though 😂😂😂😂😂😂😂😂😂',
 '3 exams this week, 3 A’s. Pass me the fucking drinks okayyyyyyy! #URL#',
 '#USER# Find me some!',
 '#USER# Soon come! 🔥',
 'RT #USER#: we went from February 1 to February 18 in 3days',
 '#USER# We’re on trimesters so this shit be moving fast af 😭😭😭😭😭 13 weeks classes smh',
 '#USER# Bitch I’m tired and I’m only on exam 3/8 tomorrow! I got 5 more to ducking go next week. When tf Ima sleep? 😂😂😂😂',
 '#USER# Oh hellllllllllllll no lmao were y’all on semesters or trimesters?',
 'RT #USER#: Your Bank account will be loaded with cash this week , Claim it ✨🦋💰🎊',
 'My studying to sleep ratio is disgusting. God gone have to sleep for me lmao #URL#',
 'I’m mf’n tired!!! And I know you know the feeling lmao #URL#',
 'I need some Addy’s bruh. I cannot 🥴 I’ve gotten a total of like 10 hours of sleep this whole week........ #URL#',
 'RT #USER#: THIS IS THE LAST STRAW!!! #URL#',
 'RT #USER#: if dick is all u have to offer, go sell it and bring me back the money',
 'I’m fucking weak! #URL#',
 '#USER# Can’t wait to return the favor! 🙃😂',
 '#USER# Thursday through Sunday, then Spring term begins 🙃🙃🙃🙃🙃🙃🙃',
 'I’m so tired it hurt to blink lmaoooooo',
 '#USER# #USER# Nevruary! Lol not until June 🥺',
 '#USER# Lmaoooo do you have to do a residency? Or you’re finished after school?',
 '#USER# I’m so tired of asking myself “Why did you do this?” 💀💀💀',
 '#USER# Lmfaoooooo at Japanese. Sounds about right!',
 '#USER# Wow! I’ve never know a vet or anyone in Vet School. That’s cool....',
 '#USER# Lmaooooo mood! What doctorate program you in?',
 '#USER# #USER# I was just looking this up yesterday lmao',
 '#USER# The damn ghetto!',
 'Nobody: Absolutely nobody: Me: Yeah Ima become a doctor. Me studying at 4:51 am: #URL#',
 'RT #USER#: ive literally pegged him i cannnoooot 😭',
 'Eyes bleeding for sure. They gotta be lol',
 '#USER# This is ghetto!',
 '4:45 am and finally closing the books 🥴',
 'What is sleep????',
 '3:00 am and still studying. I should not have to live my life like this 😭',
 '#USER# Don’t laugh at this niqqer',
 '#USER# And accounting straight math!',
 '#USER# Screaming at violent',
 '#USER# Not major 😂😂😂 this ain’t undergrad lmao',
 '#USER# Very! It’s killing me!',
 '#USER# Greatly appreciated! 🥲',
 '#USER# I need all the prayers I can get.',
 'That’s what I’m tryna do love. #URL#',
 '#USER# Idk because I don’t even wanna study.',
 '#USER# Pharmaceutical Calculations lmaooo',
 '#USER# Lmfaooooooooooooooo this picture',
 '#USER# Fuck. Basically it is lmaooo',
 'RT #USER#: Lmfaooooooo honestly, it’s going to take me a minute to feel comfortable around this even after they slow covid down lol',
 'Exam in......hours. Send fucking help! #URL#',
 '#USER# Be concussed as hell lmao that pack will knock all the alch out ya system',
 '#USER# Them shits hurts lmaooooooo',
 'Well Atlanta never closed so it really wouldn’t matter tbh lol',
 'And you deserve it all!! I be like “I know her y’all!” 😂😂😂😂 #URL# #URL#',
 'RT #USER#: I need a vacation!',
 'I’m exhausted fr man. No sleep for 2 weeks coming right up!',
 'RT #USER#: 😭😭😭 and if you’ve ever got hit you FUCKING KNOW !!! That shìt ain’t no joke',
 'RT #USER#: We was really surrounded w/ rona last year... St. Charles was a COVID cesspool 😭',
 '#USER# That’s my business my baby....']